### ISSUE TITLE
ReferenceError: PTHREADS is not defined on Debian 12 (bookworm)

### ISSUE THREAD

**Issue by jburgy** [mame/xterm-pty#34]
Hi Yusuke,

Here's what I get when I try to build `example.c` with the latest `emsdk` and a freshly installed `xterm-pty`:

```shell
~/test-emscripten-pty$ emcc -s ASYNCIFY --js-library=node_modules/xterm-pty/emscripten-pty.js -o example.mjs example.c
cache:INFO: generating system asset: symbol_lists/b1fc5dfb1bcb3b1dc219e434616f66d0cd5d206d.txt... (this will be cached in "/home/jburgy/emsdk/upstream/emscripten/cache/symbol_lists/b1fc5dfb1bcb3b1dc219e434616f66d0cd5d206d.txt" for subsequent builds)
error: failure to execute js library "/home/jburgy/test-emscripten-pty/node_modules/xterm-pty/emscripten-pty.js":
error: use -sVERBOSE to see more details
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/emscripten-core/emscripten/issues/
with a log of the build and the input files used to run. Exception message: "/home/jburgy/test-emscripten-pty/node_modules/xterm-pty/emscripten-pty.js:28
 PTHREADS
 ^

ReferenceError: PTHREADS is not defined
    at /home/jburgy/test-emscripten-pty/node_modules/xterm-pty/emscripten-pty.js:28:5
    at Script.runInThisContext (vm.js:134:12)
    at Object.runInThisContext (vm.js:310:38)
    at preprocess (/home/jburgy/emsdk/upstream/emscripten/src/parseTools.js:102:31)
    at Object.load (/home/jburgy/emsdk/upstream/emscripten/src/modules.js:214:35)
    at runJSify (/home/jburgy/emsdk/upstream/emscripten/src/jsifier.js:73:18)
    at Object.<anonymous> (/home/jburgy/emsdk/upstream/emscripten/src/compiler.js:97:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
emcc: error: '/home/jburgy/emsdk/node/14.18.2_64bit/bin/node /home/jburgy/emsdk/upstream/emscripten/src/compiler.js /tmp/tmpp89ao47j.json --symbols-only' failed (returned 1)
```

Should I create a bug report at https://github.com/emscripten-core/emscripten/issues/ as the error message suggests?  This feels specific to `xterm-pty`.  Thanks for you help and for the awesome package!

**Comment by jburgy** [comment]
NVM, upgrading emsdk to 3.1.57 fixes.  My issue was caused by a stale version of emsdk
